FROM ruby:3.2-alpine

RUN apk add --no-cache build-base gcc cmake git

WORKDIR /site

COPY blog .

RUN gem install jekyll bundler

EXPOSE 4000

CMD ["jekyll", "serve", "--host", "0.0.0.0", "--livereload"]
