name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  build:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Deploy
        run: |
          aws s3 sync ./content/blog s3://nwcalvank.dev --delete &&\
          aws cloudfront create-invalidation --distribution-id EL17OVML2MU5Z --paths "/*"
